--select * from personel

--DECLARE @Ad NVARCHAR(MAX),@Soyad NVARCHAR(MAX)
--DECLARE PERSONELCURSOR CURSOR SCROLL 
--FOR
--SELECT Ad,Soyad FROM Personel
--OPEN PERSONELCURSOR
--FETCH NEXT FROM PERSONELCURSOR INTO @Ad,@Soyad
--	PRINT @Ad + ' ' + @Soyad + ' PERSONELDIR.'
--FETCH NEXT FROM PERSONELCURSOR INTO @Ad,@Soyad
--	PRINT @Ad + ' ' + @Soyad + ' PERSONELDIR.'
--FETCH NEXT FROM PERSONELCURSOR INTO @Ad,@Soyad
--	PRINT @Ad + ' ' + @Soyad + ' PERSONELDIR.'
--CLOSE PERSONELCURSOR
--DEALLOCATE PERSONELCURSOR




DECLARE @Ad NVARCHAR(MAX),@Soyad NVARCHAR(MAX)
DECLARE PERSONELCURSOR CURSOR SCROLL 
FOR
SELECT Ad,Soyad FROM Personel
OPEN PERSONELCURSOR
FETCH NEXT FROM PERSONELCURSOR INTO @Ad,@Soyad
WHILE @@FETCH_STATUS=0 --0 : Bir önceki FETCH komutu basari ile gerçeklestirlidi.
	BEGIN
		PRINT @Ad + ' ' + @Soyad + ' PERSONELDIR.'
		FETCH NEXT FROM PERSONELCURSOR INTO @Ad,@Soyad
	END
CLOSE PERSONELCURSOR
DEALLOCATE PERSONELCURSOR








